jira:
  secret: JJTrXcSIxYGdxORxxzst48FE
  tempo-secret: fFky1JDT3PknzqV47DKEau1DKxi751
  user-name: wowbrosomeonestolemyname@gmail.com
  base-url: https://test1app2koko3.atlassian.net
  ticket-url: /rest/api/2/issue
  tickets-url: /rest/api/2/search?jql=ORDER+BY+Created&maxResults=50&startAt=0
server:
  port: 9095